name: Test Client 

on:
  pull_request:
    branches-ignore:
      - production
      - production-static
  push:
jobs:
  client-test:
    name: Client unit tests 
    runs-on: ubuntu-latest
    # needs: codegen-test-and-generate
    env:
      working-directory:  ./app.territoiresentransitions.react

    steps:
      # Note : This *should* download the artifact generated interfaces, but since it is *for now*
      #        commited, this is not needed. Once we add a github action, this should be a dependency here. 

      # cf. https://github.com/actions/checkout
      - uses: actions/checkout@v2

      # Download JavaScript models and data generated previously by codegen.
      # - name: Download generated files
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: generated-client-files
      #     path: app.territoiresentransitions.react/src/generated

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install
        working-directory: ${{env.working-directory}}

      # Use Jest to run unit tests
      - name: Jest run
        run: |
          npm run test
        working-directory: ${{env.working-directory}}
      
