name: Test Codegen and App 

on:
  pull_request:
    branches-ignore:
      - production
      - production-static
  push:
jobs:
#  end-to-end:
#    name: End-to-end tests on client
#    runs-on: ubuntu-latest
#    needs: codegen-test-and-generate
#    env:
#      working-directory:  ./app.territoiresentransitions.react
#
#    steps:
#      # cf. https://github.com/actions/checkout
#      - uses: actions/checkout@v2
#
#      # Download JavaScript models and data generated previously by codegen.
#      - name: Download generated files
#        uses: actions/download-artifact@v2
#        with:
#          name: generated-client-files
#          path: generated
#
#      # Use Cypress to run end-to-end tests
#      - name: Cypress run
#        uses: cypress-io/github-action@v2
#        with:
#          build: npm run export
#          start: npx serve __sapper__/export -p 3000
#          working-directory: ${{env.working-directory}}
#
  client-test:
    name: Client unit tests 
    runs-on: ubuntu-latest
    needs: codegen-test-and-generate
    env:
      working-directory:  ./app.territoiresentransitions.react

    steps:
      # cf. https://github.com/actions/checkout
      - uses: actions/checkout@v2

      # Download JavaScript models and data generated previously by codegen.
      - name: Download generated files
        uses: actions/download-artifact@v2
        with:
          name: generated-client-files
          path: app.territoiresentransitions.react/src/generated

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install
        working-directory: ${{env.working-directory}}

      # Use Jest to run unit tests
      - name: Jest run
        run: |
          npm run test
        working-directory: ${{env.working-directory}}
      
